### ISSUE TITLE
extra comma

### ISSUE THREAD

**Issue by yulintan** [phpactor/indexer#14]
$container->register(FileListProvider::class, function (Container $container) {
            return new FilesystemFileListProvider(
                $container->get(self::SERVICE_FILESYSTEM),
                $container->get(self::SERVICE_INDEXER_INCLUDE_PATTERNS),
                $container->get(self::SERVICE_INDEXER_EXCLUDE_PATTERNS),  //extra commma here
            );
      
php7.3 allows it but it's a breaking change for people who have to develop on php7.1. Also please update the phpactor docs requirements for vim to require 7.3+ as well as the :PhpactorStatus

**Comment by dantleech** [comment]
Hmm, Phpactor shouldn't even [install](https://github.com/phpactor/phpactor/blob/72bb79a5682babdeaad3d4b5d7a73bd60148cabb/composer.json#L12) with 7.1?

I updated Phpactors's README. 

Note you can install both 7.1 + 7.3 at the same time and configure Phpactor's [phpactorBinPath](https://phpactor.readthedocs.io/en/develop/vim-plugin/man.html) to use the 7.3 version in VIM.

How did you install Phpactor, with this extension, in a 7.1 environment?

**Comment by dantleech** [comment]
ok, I see `composer install` doesn't check the platform requirements.

I created https://github.com/phpactor/phpactor/issues/1045
