### ISSUE TITLE
exclude_pattern

### ISSUE THREAD

**Issue by fcojavierdomenech** [phpactor/indexer#41]
I'd like to exclude all my `var` folder from being indexed. Thus, my .phpactor.json settings are:

```
{
    "language_server_completion.trim_leading_dollar": true,

    "navigator.destinations":
    {
        "unit_test": "src/Domain/Tests/<kernel>Test.php",
        "mother": "src/Domain/Tests/<kernel>Mother.php",
        "source": "src/Domain/<kernel>.php"
    },

    "navigator.autocreate":
    {
        "unit_test": "default",
        "mother": "default",
        "source": "default"
    },

    "indexer.exclude_patterns": [
        "/vendor/**/Tests/**/*",
        "/vendor/**/tests/**/*",
        "/vendor/composer/**/*",
        "\/var\/**\/*",
        "/var/*",
        "var/*"
    ]
}
```

As can be seen, I've already tried with several paths, but it's still suggesting me references from the var/cache dir. Am I doing anything wrong?

**Comment by dantleech** [comment]
Obvious things first: did you `:CocCommand phpactor.reindex` (or `$ phpactor index:build --reset`) ?

**Comment by fcojavierdomenech** [comment]
sorry, yes I did a `:CocCommand phpactor.reindex` after modifying my .phpactor.json file.

Tried also closing and reopening my neovim.

Finally, I've just tried with the globally installed phpactor (`phpactor index:build --reset`) with no luck

**Comment by dantleech** [comment]
Indeed - seems not to work too well, will try and investigate.

**Comment by dantleech** [comment]
ok - no it does seem to work, it's just not very well documented:

```
        "/vendor/**/*",
```

for example will ignore my vendor directory. `*` matches up until the first `/` and `**` all chars including `/` you can test it with `phpactor index:build --reset -vvv`

**Comment by fcojavierdomenech** [comment]
It's true that on the output there are no `Updated /home/........./var/cache/....` entries. Althought phpactor is still suggesting me the var/cache references.

Maybe I should delete manually some old phpactor indexes or cache?

**Comment by dantleech** [comment]
Both `phpactor index:build --reset` and `phpactor.reindex` should do that ... AFAIRC. But if you want to be sure `rm -Rf ~/.cache/phpactor/index/<project dir name>-<some hash>`. And you'll need to restart the Language Server - maybe ..

**Comment by fcojavierdomenech** [comment]
I've been looking a bit more into it.... indeed, it weren't phpactor sugestions. I didn't notice I had an inteliphense extension set up also, so It was a mix of both, phpactor and phpls. Once I excluded forders in both, everything is working fine.

My apologies for the inconvenience.
